"""rename date_of to grade_date

Revision ID: fa5ec242d765
Revises: 3616fc64e638
Create Date: 2026-07-05 15:25:56.342760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5ec242d765'
down_revision: Union[str, Sequence[str], None] = '3616fc64e638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('grade_date', sa.Date(), nullable=True))
    op.drop_column('grades', 'date_of')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date_of', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('grades', 'grade_date')
    # ### end Alembic commands ###
